# Generated by Django 3.1.6 on 2021-02-18 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bot',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='bot',
            name='times_bought',
        ),
        migrations.AddField(
            model_name='bot',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
