# Generated by Django 3.1.6 on 2021-02-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0002_auto_20210218_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={'verbose_name': 'Bots'},
        ),
        migrations.AlterModelTable(
            name='bot',
            table='Bots',
        ),
    ]
