# Generated by Django 3.1.5 on 2021-03-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20210219_1617'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bot',
            options={},
        ),
        migrations.AddField(
            model_name='bot',
            name='author',
            field=models.CharField(default='Admin', max_length=100),
        ),
    ]
