# Generated by Django 3.1.5 on 2021-03-16 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_auto_20210304_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='bot',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
