# Generated by Django 3.1.5 on 2021-03-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_bot_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bot',
            name='file',
            field=models.FileField(default='bots/no_script.txt', upload_to=''),
        ),
    ]
